### ISSUE TITLE
Enable rendering a PDF from inside a notebook

### ISSUE THREAD

**Issue by clausmith** [onecodex/docker-onecodex-notebook#11]
It would be sweet if we could render an HTML string to a PDF file from within the notebook itself. The basics are in place for this, since we just need `weasyprint` to be accessible from within a notebook.

**Comment by polyatail** [comment]
I think this is possible by editing the dropdown js (currently served by nginx, see #15) to include our weasyprint route, which we can do by extending nbconvert (see https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/base.py).

**Comment by polyatail** [comment]
Closing in favor of https://github.com/onecodex/onecodex/issues/184.
