### ISSUE TITLE
Notebook occasionally crashes with WebDriverException

### ISSUE THREAD

**Issue by clausmith** [onecodex/docker-onecodex-notebook#26]
I see this consistently on my Mac (i.e. I can't save Altair plots using the Docker image locally), and saw this a handful of times in production when rendering notebooks:

```
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.14.128-112.105.amzn2.x86_64 x86_64)
```

**Comment by Keats** [comment]
Oh I had the exact same issue on GH actions when configuring integration tests. The issue in my case was that Chrome was crashing in docker and I had to pass those arguments: https://github.com/onecodex/mainline/pull/3479/files#diff-38662eda33df859414dcfaa49bac04b2R92 to make it work.
