### ISSUE TITLE
Raven import fails in Docker (library installation issue with conda to debug)

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/docker-onecodex-notebook#5]
Here's the error we see: `"AttributeError: module 'certifi' has no attribute 'where'"`

**Comment by clausmith** [comment]
Closed by onecodex/docker-scipy-notebook/commit/85f499c

**Comment by boydgreenfield** [comment]
Woohoo, this is fixed (verified on our notebooks infrastructure too).
